# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipenv and dependencies via pipenv
      run: |
        python -m pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        # will automatically pickup config in tox.ini
        pipenv run flake8 .
    - name: Check import ordering
      run: |
        pipenv run isort . -c
    - name: Unit tests
      run: |
        pipenv run python manage.py test
